Double-check the debootstrap result
Debootstrap sometimes fails to setup packages, especially when the
dependencies aren't available. In this case it helpfully reports success
as it's exit code. Checking in the chroot if everything was left
unconfigured (and whether configuring that fails) detects these cases.

Also in such a case output the debootstrap log so it's easier to analyse
the problem.

Signed-off-by: Héctor Orón Martínez <hector.oron@collabora.co.uk>

diff --git a/init_buildsystem b/init_buildsystem
--- a/init_buildsystem
+++ b/init_buildsystem
@@ -770,7 +770,11 @@ if test ! -f $BUILD_ROOT/var/lib/rpm/packages.rpm -a ! -f $BUILD_ROOT/var/lib/rp
 		# Run debootstrap
 		set -- debootstrap --variant=buildd --arch=$DEBOOT_ARCH --include=$FULL_PKG_LIST obs $BUILD_ROOT file://$BUILD_ROOT/obs_repo
 		echo "$@ ..."
-		$@
+		if ! $@ || ! chroot $BUILD_ROOT dpkg --configure -a; then
+			cat $BUILD_ROOT/debootstrap/debootstrap.log
+			echo "Failed to setup debootstrap chroot"
+			cleanup_and_exit 1
+		fi
 	else
 		progress_setup PACKAGES_TO_PREINSTALL
 		for PKG in $PACKAGES_TO_PREINSTALL ; do
